# Keep the test database lifecycle local to the test suite so EzAuth always
# migrates from the same installer output a host application would receive.
_ = Ecto.Adapters.Postgres.storage_down(EzAuth.TestRepo.config())
:ok = Ecto.Adapters.Postgres.storage_up(EzAuth.TestRepo.config())

# Refresh the generated migrations before each test run. `--replace` updates
# the existing EzAuth migration files in place instead of creating duplicates.
Mix.Task.run("ez_auth.install", ["--replace"])

EzAuth.TestRepo.start_link()

# Run migrations programmatically because the migration files are generated by
# the previous step, after Mix aliases have handed control to the test suite.
Ecto.Migrator.run(EzAuth.TestRepo, :up, all: true, log: false)

Ecto.Adapters.SQL.Sandbox.mode(EzAuth.TestRepo, :manual)

EzAuth.Test.Endpoint.start_link()

Mimic.copy(EzAuth.Accounts)
Mimic.copy(EzAuth.Auth)
Mimic.copy(EzAuth.Config)
Mimic.copy(EzAuth.OAuth.Shared)
Mimic.copy(EzAuth.OAuth.Apple)
Mimic.copy(EzAuth.Test.Endpoint)
Mimic.copy(EzAuth.Test.Sender)
Mimic.copy(EzAuth.Test.Handler)
Mimic.copy(EzAuth.Test.Strategy)
Mimic.copy(Req)

ExUnit.start()
