# This file was generated by `mix ez_auth.install`.
# Regenerate it by rerunning the installer after updating EzAuth.

defmodule EzAuth.TestRepo.Migrations.EzAuthPrepareDatabase do
  use Ecto.Migration

  def change do
    execute "CREATE EXTENSION IF NOT EXISTS citext", ""
    execute "CREATE SCHEMA IF NOT EXISTS auth", "DROP SCHEMA IF EXISTS auth"
  end
end
