# This file was generated by `mix ez_auth.install`.
# Regenerate it by rerunning the installer after updating EzAuth.

defmodule EzAuth.TestRepo.Migrations.EzAuthCreateClaims do
  use Ecto.Migration

  def change do
    create table(:claims, prefix: "auth") do
      add :user_id, references(:users, prefix: "auth", on_delete: :delete_all), null: false
      add :scope, :string, null: false, default: "default"
      add :value, :string, null: false

      timestamps(type: :utc_datetime)
    end

    create unique_index(:claims, [:user_id, :scope, :value], prefix: "auth")
    create index(:claims, [:user_id, :scope], prefix: "auth")
    create index(:claims, [:scope, :value], prefix: "auth")
  end
end
